// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HealthChartController from "./health_chart_controller"
application.register("health-chart", HealthChartController)

import MatchBuildsController from "./match_builds_controller"
application.register("match-builds", MatchBuildsController)

import PopoverController from "./popover_controller"
application.register("popover", PopoverController)

import ProfessionNavController from "./profession_nav_controller"
application.register("profession-nav", ProfessionNavController)

import TooltipController from "./tooltip_controller"
application.register("tooltip", TooltipController)
