// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HealthChartController from "./health_chart_controller"
application.register("health-chart", HealthChartController)

import MatchBuildsController from "./match_builds_controller"
application.register("match-builds", MatchBuildsController)

import ProfessionNavController from "./profession_nav_controller"
application.register("profession-nav", ProfessionNavController)

import SearchDialogController from "./search_dialog_controller"
application.register("search-dialog", SearchDialogController)

import TemplateCodePopoverController from "./template_code_popover_controller"
application.register("template-code-popover", TemplateCodePopoverController)

import TooltipController from "./tooltip_controller"
application.register("tooltip", TooltipController)

import VariantTabsController from "./variant_tabs_controller"
application.register("variant-tabs", VariantTabsController)
